apiVersion: v1
kind: Service
metadata:
  name: @appName@
spec:
  # 외부 노출을 위한 NodePort 타입 (로드밸런서 사용 시 LoadBalancer로 변경)
  type: NodePort
  selector:
    app: @appName@
  ports:
  - port: 8080       # 서비스 내부 포트
    targetPort: 8080 # 컨테이너 포트
    nodePort: 30080  # 외부 접근 포트 (고정값 예시, 필요 시 변경)
