Configuration:
  status: warn
  Appenders:
    Console:
      name: Console
      target: SYSTEM_OUT
      PatternLayout:
        Pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    RollingFile:
      name: File
      fileName: "${sys:log.path}/${sys:app.name}.log"
      filePattern: "${sys:log.path}/${sys:app.name}-%d{yyyy-MM-dd}-%i.log.gz"
      PatternLayout:
        Pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
      Policies:
        TimeBasedTriggeringPolicy:
          interval: 1
          modulate: true
        SizeBasedTriggeringPolicy:
          size: "10 MB"
      DefaultRolloverStrategy:
        max: 10
  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: Console
        - ref: File
